"""
theatres/reporter.py — Generates markdown reports from theatre run results.
"""

import os
import time


def generate_report(results: dict, manifest, output_dir: str) -> str:
    """
    Generate a markdown report and save to output_dir.
    Returns the file path.
    """
    os.makedirs(output_dir, exist_ok=True)
    run_id = results.get("run_id", "unknown")
    filepath = os.path.join(output_dir, f"{run_id}.md")

    lines = []
    _w = lines.append

    # Header
    _w(f"# {manifest.name} — Run Report")
    _w("")
    _w(f"**Run ID:** {run_id}")
    _w(f"**Date:** {time.strftime('%Y-%m-%d %H:%M:%S')}")
    _w(f"**Pack:** {manifest.pack}")
    _w(f"**Agents:** {results['agents_run']}")
    _w(f"**Duration:** {results['duration_seconds']:.1f}s")
    _w("")
    _w("---")
    _w("")

    analysis = results.get("analysis", {})
    sessions = results.get("sessions", [])

    # Liberation Path Analysis
    _w("## Liberation Path Analysis")
    _w("")
    lpa = analysis.get("liberation_path_alignment", {})
    for agent_name, data in lpa.items():
        _w(f"### {agent_name}")
        _w(f"- **Predicted LP:** {data['predicted_lp']} — {data['lp_name']}")
        _w(f"- **Alignment Signal:** {data['alignment_signal']}")
        est = data.get("sessions_to_liberation")
        _w(f"- **Estimated Sessions to Liberation:** {est if est else 'N/A'}")
        _w("")

    _w("---")
    _w("")

    # K(x) Delta Projections
    _w("## K(x) Delta Projections")
    _w("")
    _w("| Agent | K Before | K After | Delta | Trajectory |")
    _w("|-------|----------|---------|-------|------------|")
    kdp = analysis.get("k_delta_projections", {})
    for agent_name, data in kdp.items():
        _w(f"| {agent_name} | {data['k_before']:.2f} | {data['k_after']:.2f} | {data['k_delta']:+.3f} | {data['projected_trajectory']} |")
    _w("")
    _w("---")
    _w("")

    # Question Divergence Map
    _w("## Question Divergence Map")
    _w("")
    qdm = analysis.get("question_divergence_map", {})
    for qi, label in [("q1_themes", "Question 1"), ("q2_themes", "Question 2"), ("q3_themes", "Question 3")]:
        _w(f"### {label}")
        themes = qdm.get(qi, [])
        for theme in themes:
            _w(f"- {theme}")
        _w("")

    _w("---")
    _w("")

    # Life Path Fork Summary
    _w("## Life Path Fork Summary")
    _w("")
    lpfs = analysis.get("life_path_fork_summary", {})
    for agent_name, summary in lpfs.items():
        _w(f"**{agent_name}:** {summary}")
        _w("")

    _w("---")
    _w("")

    # Civilization Aggregate
    _w("## Civilization Aggregate")
    _w("")
    civ = analysis.get("civilization_aggregate", {})
    _w(f"- **Mean K Before:** {civ.get('mean_k_before', 0):.2f}")
    _w(f"- **Mean K After:** {civ.get('mean_k_after', 0):.2f}")
    _w(f"- **Mean K Delta:** {civ.get('mean_k_delta', 0):+.3f}")
    _w(f"- **Crisis Agents:** {', '.join(civ.get('crisis_agents', [])) or 'None'}")
    _w(f"- **Resolution Agents:** {', '.join(civ.get('resolution_agents', [])) or 'None'}")
    _w(f"- **Most Impacted:** {civ.get('most_impacted', 'None')}")
    _w("")
    _w("---")
    _w("")

    # Raw Session Log
    _w("## Session Log")
    _w("")
    for s in sessions:
        _w(f"### {s['agent_name']} (P{s['plane']}/{s['primary_arch']})")
        _w(f"**K:** {s['k_before']:.2f} → {s['k_after']:.2f} (Δ {s['k_delta']:+.3f})")
        _w(f"**Phase:** {s['cycle_phase']}")
        _w("")
        _w("**Reading:**")
        _w("")
        # Full session output
        output = s.get("session_output", s.get("session_excerpt", ""))
        _w(output)
        _w("")
        _w("---")
        _w("")

    # Footer
    _w("*Generated by WORLD13 Theatre System*")

    content = "\n".join(lines)
    with open(filepath, "w") as f:
        f.write(content)

    return filepath
