#!/usr/bin/env python3
"""
scripts/export_world_chronicle.py

Export the world vault to a readable markdown chronicle.

Usage:
    python3 scripts/export_world_chronicle.py
    python3 scripts/export_world_chronicle.py --db data/world13_world.db
    python3 scripts/export_world_chronicle.py --ticks 1-50
"""

import sys
import os
import argparse
import sqlite3
import datetime

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def export_chronicle(db_path: str, tick_range: tuple = None, output_path: str = None) -> str:
    if not os.path.exists(db_path):
        print(f"Error: database not found at {db_path}")
        sys.exit(1)

    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row

    # Get all vault records ordered by creation time
    rows = conn.execute("""
        SELECT
            v.id, v.dim_pack, v.dim_user as agent_id, v.dim_date,
            v.dim_content, v.k_value_at_session, v.k_delta,
            v.lambda_at_session, v.coherence_at_session,
            v.cycle_phase, v.plane, v.created_at,
            a.name as agent_name, a.primary_arch, a.is_liberated
        FROM vault_records v
        LEFT JOIN agents a ON v.dim_user = a.id
        ORDER BY v.created_at ASC
    """).fetchall()

    # Get all agents
    agents = conn.execute(
        "SELECT name, k_current, lambda_coeff, is_liberated, sessions_completed FROM agents ORDER BY created_at"
    ).fetchall()

    conn.close()

    if not rows:
        print("No sessions found in vault.")
        sys.exit(0)

    if not output_path:
        os.makedirs("data/world_logs", exist_ok=True)
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        output_path = f"data/world_logs/chronicle_export_{timestamp}.md"

    lines = []
    _w = lines.append

    _w("# WORLD13 — Chronicle Export\n")
    _w(f"**Exported:** {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    _w(f"**Database:** {db_path}")
    _w(f"**Total sessions:** {len(rows)}")
    _w(f"**Agents:** {len(agents)}")
    _w("")

    _w("## The World\n")
    _w("| Name | Final K | λ | Sessions | Status |")
    _w("|------|---------|---|----------|--------|")
    for a in agents:
        status = "★ Completed" if a["is_liberated"] else "Living"
        _w(f"| {a['name']} | {a['k_current']:.2f} | {a['lambda_coeff']:.2f} | "
           f"{a['sessions_completed']} | {status} |")
    _w("")
    _w("---\n")

    # Group sessions into ticks (every 2 sessions = 1 tick for world-fast)
    sessions_per_tick = 2
    _w("## Sessions\n")

    tick_num = 0
    for i, row in enumerate(rows):
        if i % sessions_per_tick == 0:
            tick_num += 1
            if tick_range:
                if tick_num < tick_range[0]:
                    continue
                if tick_num > tick_range[1]:
                    break
            _w(f"### Tick {tick_num}\n")

        if tick_range and (tick_num < tick_range[0] or tick_num > tick_range[1]):
            continue

        agent_name = row["agent_name"] or "Unknown"
        event = row["dim_pack"] or "a moment"
        k = row["k_value_at_session"] or 0
        delta = row["k_delta"] or 0
        is_liberated = bool(row["is_liberated"])
        content = row["dim_content"] or ""

        first_sentence = ""
        if content:
            for s in content.replace("\n", " ").split("."):
                s = s.strip()
                if s and not s.startswith("#") and not s.startswith("*") and not s.startswith("[") and len(s) > 20:
                    first_sentence = s[:150]
                    if len(s) > 150:
                        first_sentence += "..."
                    break

        if is_liberated and k is not None and k < 0.1:
            _w(f"**★ {agent_name} — something completes.**")
            if first_sentence:
                _w(f"\n> {first_sentence}.")
        else:
            _w(f"**{agent_name}** — {event}  `K:{k:.2f}  Δ:{delta:+.3f}`")
            if first_sentence:
                _w(f"\n> {first_sentence}.")

        _w("")

    _w("---\n")
    _w(f"*Generated by WORLD13 chronicle export — {len(rows)} sessions*")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    return output_path


def parse_tick_range(s: str) -> tuple:
    if "-" in s:
        parts = s.split("-")
        return (int(parts[0]), int(parts[1]))
    return (1, int(s))


def main():
    parser = argparse.ArgumentParser(description="Export WORLD13 vault to markdown chronicle")
    parser.add_argument("--db", default="data/world13_world.db", help="Path to world vault database")
    parser.add_argument("--ticks", help="Tick range to export, e.g. '1-50'")
    parser.add_argument("--output", help="Output file path")
    args = parser.parse_args()

    tick_range = parse_tick_range(args.ticks) if args.ticks else None
    output_path = export_chronicle(args.db, tick_range, args.output)

    print(f"Chronicle exported: {output_path}")


if __name__ == "__main__":
    main()
